get:
  operationId: GetClientTaskLog
  deprecated: true
  summary: Get client task log
  description: This endpoint has been deprecated. Please use `GET /api/v2/jobs/{job_id}/log` instead.
  tags:
    - Tasks
    - Enterprise
  security: []
  responses: {}
