allOf:
  - $ref: './components/int32.id.yaml'
  - $ref: './components/timestamps.yaml'
type: object
properties:
  key:
    type: string
  value:
    type: object
  name:
    type: string
    readOnly: true
  description:
    type: string
    readOnly: true
