parameters:
  - $ref: './../../parameters/header/prefer.yaml'

get:
  operationId: ListAppConfigParams
  summary: List application config parameters
  description: Lists application configuration parameters for this instance
  tags:
    - Config
    - Community
    - Enterprise
  parameters:
    - name: parameter
      description: >
        Parameter filter. Must follow the convention: parameter=eq:value
      in: query
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: './../../schemas/model/app-config-param.yaml'
    400:
      $ref: './../../responses/bad-request.yaml'
    401:
      $ref: './../../responses/unauthorized.yaml'
    403:
      $ref: './../../responses/forbidden.yaml'
    429:
      $ref: './../../responses/too-many-requests.yaml'
    500:
      $ref: './../../responses/internal-server-error.yaml'

put:
  operationId: SetAppConfigParam
  summary: Write application configuration parameters
  description: Writes application configuration parameters for this instance
  tags:
    - Config API
    - Community
    - Enterprise
  requestBody:
    description: The request body for updating an application config parameter
    required: true
    content:
      application/json:
        schema:
          $ref: './../../schemas/model/app-config-param.yaml'
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: object
    400:
      $ref: './../../responses/bad-request.yaml'
    401:
      $ref: './../../responses/unauthorized.yaml'
    403:
      $ref: './../../responses/forbidden.yaml'
    429:
      $ref: './../../responses/too-many-requests.yaml'
    500:
      $ref: './../../responses/internal-server-error.yaml'
