parameters:
  - $ref: './../../parameters/header/prefer.yaml'
get:
  operationId: ListFeatureFlags
  summary: List feature flags
  description: Lists all feature flags for this instance
  tags:
    - Config API
    - Community
    - Enterprise
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: './../../schemas/model/feature-flag.yaml'
    401:
      $ref: './../../responses/unauthorized.yaml'
    403:
      $ref: './../../responses/forbidden.yaml'
    429:
      $ref: './../../responses/too-many-requests.yaml'
    500:
      $ref: './../../responses/internal-server-error.yaml'
