parameters:
  - type: string
    description: Feature ID
    name: feature_id
    in: path
    required: true
put:
  description: Writes application configuration parameters for this instance
  tags:
    - Config API
    - Community
    - Enterprise
  summary: Toggle a feature flag's enabled status to either enable or disable it.
  parameters:
    - $ref: './../../parameters/header/prefer.yaml'
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/definitions/api.BasicResponse"
    default:
      $ref: './../../responses/api/error-response.yaml'
