get:
  description: Lists all feature flags for this instance
  tags:
    - Config API
    - Community
    - Enterprise
  summary: List feature flags
  parameters:
    - $ref: './../../parameters/header/prefer.yaml'
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/definitions/api.BasicResponse"
    default:
      $ref: './../../responses/api/error-response.yaml'
